/* tslint:disable */
/* eslint-disable */
/**
 * Gator API
 * A RESTful API for Gator
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Building,
  BuildingPage,
} from '../models';
import {
    BuildingFromJSON,
    BuildingToJSON,
    BuildingPageFromJSON,
    BuildingPageToJSON,
} from '../models';

export interface GetBuildingRequest {
    code: string;
    xFields?: string;
}

export interface ListBuildingsRequest {
    lastId?: string;
    pageSize?: number;
    xFields?: string;
}

/**
 * 
 */
export class BuildingsApi extends runtime.BaseAPI {

    /**
     * Args:     code: The code of the building.
     * Fetch the building with the given code
     */
    async getBuildingRaw(requestParameters: GetBuildingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Building>> {
        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling getBuilding.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xFields !== undefined && requestParameters.xFields !== null) {
            headerParameters['X-Fields'] = String(requestParameters.xFields);
        }

        const response = await this.request({
            path: `/buildings/{code}`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BuildingFromJSON(jsonValue));
    }

    /**
     * Args:     code: The code of the building.
     * Fetch the building with the given code
     */
    async getBuilding(requestParameters: GetBuildingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Building> {
        const response = await this.getBuildingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts query parameters:     page_size: number of items to return per page (default: 20).     last_id: id of the last item returned. If not specified, returns the first page.  Returns:     A dictionary containing the following keys:         buildings: A list of buildings up to the specified page size.         last_id: The id of the last item returned.
     * List all buildings
     */
    async listBuildingsRaw(requestParameters: ListBuildingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BuildingPage>> {
        const queryParameters: any = {};

        if (requestParameters.lastId !== undefined) {
            queryParameters['last_id'] = requestParameters.lastId;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['page_size'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xFields !== undefined && requestParameters.xFields !== null) {
            headerParameters['X-Fields'] = String(requestParameters.xFields);
        }

        const response = await this.request({
            path: `/buildings/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BuildingPageFromJSON(jsonValue));
    }

    /**
     * Accepts query parameters:     page_size: number of items to return per page (default: 20).     last_id: id of the last item returned. If not specified, returns the first page.  Returns:     A dictionary containing the following keys:         buildings: A list of buildings up to the specified page size.         last_id: The id of the last item returned.
     * List all buildings
     */
    async listBuildings(requestParameters: ListBuildingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BuildingPage> {
        const response = await this.listBuildingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
