/* tslint:disable */
/* eslint-disable */
/**
 * Gator API
 * A RESTful API for Gator
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeeklyRepetitionScheduleDump
 */
export interface WeeklyRepetitionScheduleDump {
    /**
     * 
     * @type {boolean}
     * @memberof WeeklyRepetitionScheduleDump
     */
    isAlternating?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof WeeklyRepetitionScheduleDump
     */
    weeks?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof WeeklyRepetitionScheduleDump
     */
    schedule?: number;
    /**
     * 
     * @type {string}
     * @memberof WeeklyRepetitionScheduleDump
     */
    scheduleBits?: string;
}

/**
 * Check if a given object implements the WeeklyRepetitionScheduleDump interface.
 */
export function instanceOfWeeklyRepetitionScheduleDump(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WeeklyRepetitionScheduleDumpFromJSON(json: any): WeeklyRepetitionScheduleDump {
    return WeeklyRepetitionScheduleDumpFromJSONTyped(json, false);
}

export function WeeklyRepetitionScheduleDumpFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeeklyRepetitionScheduleDump {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isAlternating': !exists(json, 'is_alternating') ? undefined : json['is_alternating'],
        'weeks': !exists(json, 'weeks') ? undefined : json['weeks'],
        'schedule': !exists(json, 'schedule') ? undefined : json['schedule'],
        'scheduleBits': !exists(json, 'schedule_bits') ? undefined : json['schedule_bits'],
    };
}

export function WeeklyRepetitionScheduleDumpToJSON(value?: WeeklyRepetitionScheduleDump | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_alternating': value.isAlternating,
        'weeks': value.weeks,
        'schedule': value.schedule,
        'schedule_bits': value.scheduleBits,
    };
}

